name: SubModule

on:

  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:

  push-submodule-branch:
    name: Push branch for git-submodule
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          repository: "NaokiHori/SimpleDecomp"
          ref: "main"
      - name: Configure git
        run: |
          git switch -c submodule
          git config --local user.email "36466440+NaokiHori@users.noreply.github.com"
          git config --local user.name "NaokiHori"
      - name: Remove unnecessary files
        run: |
          git rm -r .github
          git rm Makefile
          git rm README.rst
          git rm -r docs
          git rm install.sh
          git rm src/main.c
          git rm -r test
      - name: Commit changes and push branch
        run: |
          git commit -m "remove files for git submodule" -a || true
          git push -f origin submodule

